Forum/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('livechat.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('profile.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', IndexView.as_view()),
    path('announce/', include('announcement.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import IndexView, AnnounceView, NewAnnounceView

urlpatterns = [
    path('', IndexView.as_view()),
    path('announce/new/', NewAnnounceView.as_view()),
]

main/models.py
import django.utils.timezone
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """ Категория объявления форума """
    name = models.CharField(max_length=50, null=False)

    def __str__(self):
        return self.name


class Announcement(models.Model):
    """ Модель объявления форума """
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=False)
    text = models.CharField(max_length=555, null=False)
    date = models.DateTimeField(default=django.utils.timezone.now)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title if len(self.title) < 25 else self.title[:22] + '...'

    class Meta:
        ordering = ('-date', )


class Response(models.Model):
    """ Отклик на объявлление форума """
    is_accept = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=300, null=False)
    date = models.DateTimeField(default=django.utils.timezone.now)

    class Meta:
        ordering = ('-date', )

templates/announce/detail.html
{% extends 'main.html' %}
{% block title %}Создание объявления{% endblock title %}
{% block extra_head %}
    {% load static %}
    {% load humanize %}
{% endblock extra_head %}
{% block body %}
<div class="card">
    <div class="card-header">{{ object.title }}</div>
    <div class="card-body">
        {{ object.text|safe }}
    </div>
    <div class="card-footer d-flex flex-row">
        <div class="flex-grow-1">
            Автор: {{ object.author }}<br>
            {{ object.date }}<br>
            {{ object.data|timesince }}
        </div>
        {% if request.user == object.author %}
            <div>
                <a class="btn btn-outline-primary" href="/announce/edit/{{ object.pk }}">Редактировать объявление</a>
            </div>
        {% endif %}
    </div>
</div>
{% if inactive_response %}
    <div class="card my-2">
    <div class="card-header">Отзывы, ожидающие подтверждения</div>
    <div class="card-body">
        {% for comm in inactive_response %}
            <div class="card my-2">
                <div class="card-header">{{ comm.author }}</div>
                <div class="card-body">{{ comm.text }}</div>
                <div class="card-footer d-flex">
                    <div class="flex-grow-1">{{ comm.date }}</div>
                    <div class="btn-group" role="group">
                      <button type="button" class="btn btn-outline-success" id="accept_response" value="{{ comm.pk }}">Разрешить</button>
                      <button type="button" class="btn btn-outline-danger" id="remove_response" value="{{ comm.pk }}">Запретить</button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endif %}
<div class="card my-2">
    <div class="card-header">Отзывы</div>
    <div class="card-body">
        {% if request.user.is_authenticated %}
            <form id="response_form">
                <input name="announce" value="{{ object.pk }}" type="hidden">
                <label class="form-label" for="response_text">Текст</label>
                <textarea class="form-control" name="text" id="response_text" cols="30" rows="5" maxlength="300"></textarea>
                <button class="btn btn-outline-success my-2" type="submit">Отправить отзыв</button>
            </form>
            <div id="responce_succsess" class="p-1 d-none">
                Ваш отзыв успешно отправлен! Как только автор объявления проверит его и утвердит, он будет добавлен на страницу!
            </div>
        {% else %}
            Отзывы могут отправлять только авторизованные пользователи.
        {% endif %}
    </div>
    <div class="card-footer">
        {% if not response %}
            <h3>Комментариев пока нет! Будьте первым!</h3>
        {% else %}
            {% for comm in response %}
            <div class="card my-2">
                <div class="card-header">{{ comm.author }}</div>
                <div class="card-body">{{ comm.text }}</div>
                <div class="card-footer">
                    {{ comm.date }}
                </div>
            </div>
            {%  endfor %}
        {% endif %}
   </div>
</div>
{% endblock body %}
{% block scripts %}
    <script src="{% static 'response.js' %}"></script>
{% endblock scripts %}

templates/announce/edit.html
{% extends 'main.html' %}
{% block title %}Редактирование объявления{% endblock title %}

{% block body %}
<div class="card">
    <div class="card-header">Редактирование объявления</div>
    <div class="card-body">
        <form method="post">{% csrf_token %}
            <label class="form-label" for="id_title">Заголовок</label>
            <input class="form-control" id="id_title" name="title" type="text" value="{{ object.title }}" maxlength="255" required>
            Категория
            <div class="border rounded p-2 my-2">
                <div class="row row-cols-4">
                    {% for category in categories %}
                        <div class="col">
                            <div class="form-check">
                                <input class="form-check-input" name="category" value="{{ category.pk }}" id="id_{{ category.name }}" {% if object.category.pk == category.pk %}checked{% endif %} type="radio">
                                <label class="form-check-label" for="id_{{ category.name }}">{{ category.name }}</label>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="border rounded p-1 bg-body summernote-div">
                {{ form.media }}
                {{ form.text }}
            </div>
            <button class="btn btn-outline-success my-2" type="submit">Принять изменения</button>
        </form>
    </div>
</div>
{% endblock body %}
{% block scripts %}
{% endblock scripts %}

templates/announce/new.html
{% extends 'main.html' %}
{% block title %}Создание объявления{% endblock title %}

{% block body %}
<div class="card">
    <div class="card-header">Создание объявления</div>
    <div class="card-body">
        <form method="post">{% csrf_token %}
            <label class="form-label" for="id_title">Заголовок</label>
            <input class="form-control" id="id_title" name="title" type="text" maxlength="255" required>
            Категория
            <div class="border rounded p-2 my-2">
                <div class="row row-cols-4">
                    {% for category in categories %}
                        <div class="col">
                            <div class="form-check">
                                <input class="form-check-input" name="category" value="{{ category.pk }}" id="id_{{ category.name }}" type="radio">
                                <label class="form-check-label" for="id_{{ category.name }}">{{ category.name }}</label>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="border rounded p-1 bg-body summernote-div">
                {{ form.media }}
                {{ form.text }}
            </div>
            <button class="btn btn-outline-success my-2" type="submit">Опубликовать</button>
        </form>
    </div>
</div>
{% endblock body %}
{% block scripts %}
{% endblock scripts %}